In [17]:
import pandas as pd
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import os, math
from functools import reduce
from PyEMD import EMD, Visualisation
import statsmodels.api as sm
%matplotlib inline

学习一下包络算法大致上是怎么做的
首先， 我们需要计算滚动轴承的一些基本参数

BPFO， 外圈故障频率  $ BPFO = \dfrac{nf_s}{2}\left\{ 1 + \dfrac{d}{D} cos \alpha \right\} $

BPFI， 内圈故障频率  $ BPFI = \dfrac{nf_s}{2}\left\{ 1 - \dfrac{d}{D} cos \alpha \right\} $

FTF,   轴承基本频率  $ FTF = \dfrac{f_s}{2}\left\{1-\dfrac{d}{D}cos\alpha\right\} $

BSF，  滚珠故障频率  $ BSF = \dfrac{Df_s}{d}\left\{1-\left( \dfrac{d}{D}cos\alpha \right)^2\right\} $

其中$ D, d, \alpha, n, f_s $ 分别代表轴承直径， 滚珠直径， 滚珠和保持架的接触角， 滚珠个数， 轴承旋转频率。

In [11]:
f_s = 35
pitch_diameter = 39.80 * 1 / 1000
ball_diameter = 7.92 * 1 / 1000
contact_angle = 0
n_balls = 8
filename = "./35Hz12kN/Bearing1_1/100.csv"
df = pd.read_csv(filename)
df = df.rename(columns={"Horizontal_vibration_signals":"H", "Vertical_vibration_signals":"V"})

In [12]:
# 计算轴承的基本参数

bpfo = n_balls * f_s / 2.0 * ( 1 + ball_diameter / pitch_diameter) * math.cos(contact_angle)
bpfi = n_balls * f_s / 2.0 * ( 1 - ball_diameter /pitch_diameter ) * math.cos(contact_angle)
ftf = f_s / 2.0 * (1 - ball_diameter/pitch_diameter) * math.cos(contact_angle)
bsf = pitch_diameter * f_s / ball_diameter * ( 1 - ((ball_diameter / pitch_diameter)*math.cos(contact_angle))**2)

In [19]:
# 查找合适的arma参数
max_iterator = 400


for order in range(max_iterator):
    a = sm.regression.linear_model.yule_walker(df.V, order+1)
    print(a)
    

(array([0.73844869]), 1.5547469793264808)
(array([0.40139373, 0.45643653]), 1.3833454146656232)
(array([0.3971586 , 0.45271212, 0.00927869]), 1.383285864511734)
(array([ 0.39946036,  0.5650159 ,  0.10780136, -0.24806885]), 1.340047672847278)
(array([ 0.32870684,  0.59576271,  0.26895365, -0.13413587, -0.28521725]), 1.2843859696948616)
(array([ 0.21801088,  0.5437031 ,  0.37333752,  0.09708621, -0.15764251,
       -0.38811102]), 1.183706329156465)
(array([ 0.09609754,  0.49418447,  0.40383422,  0.2143589 ,  0.01314539,
       -0.31962949, -0.31411977]), 1.123791094982051)
(array([ 0.06176835,  0.45925314,  0.40527084,  0.23778553,  0.05727919,
       -0.26562158, -0.30361757, -0.10928694]), 1.117059860264653)
(array([ 0.07199066,  0.48765246,  0.43011615,  0.23242784,  0.03503757,
       -0.30352919, -0.34657449, -0.11506453,  0.09353648]), 1.1121625059511138)
(array([ 0.08801119,  0.4679447 ,  0.37075636,  0.18044066,  0.04103866,
       -0.26371995, -0.27290605, -0.03154152,  0.105866